// <auto-generated />
namespace Microsoft.AspNetCore.Mvc.Formatters.Xml.Extensions
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("Microsoft.AspNetCore.Mvc.Formatters.Xml.Extensions.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        ///   The XML formatter {0} was not added MVC, use proper  AddXml...Formatters() extension..
        /// </summary>
        public static string XmlFromater_WasNotSetup_To_Mvc(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("XmlFromater_WasNotSetup_To_Mvc"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
